# Generated by Django 3.0.5 on 2020-05-13 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 5, 13, 15, 8, 14, 178739, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
